// Show ip - displays the ip of a host given on the command line
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <netinet/in.h>


int main(int argc, char *argv[])
{
    int status;                               // Used for error checking
    struct addrinfo hints, *res, *p;          // Helps getaddrinfo get the right info
    char ipstr[INET6_ADDRSTRLEN];

    if (argc != 2)
    {
        fprintf(stderr, "Usage: showip hostanme\n");
        return 1;
    }

    // Make sure the struct hints is empty
    memset(&hints, 0, sizeof(hints));

    hints.ai_family = AF_UNSPEC;                // Use IPv4 or IPv6 
    hints.ai_socktype = SOCK_STREAM;            // Use TCP stream sockets
    //hints.ai_flags = AI_PASSIVE;                // Fill in my ip for me

    // Fill in the info about this computer and check to see if it was successful
    if ((status = getaddrinfo(argv[1], NULL, &hints, &res)) != 0)
    {
        fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(status));
        return 2;
    }

    printf("IP addresses for %s:\n\n", argv[1]);

    for (p = res; p != NULL; p = p->ai_next)
    {
        void *addr;
        char *ipver;

        // Get the pointer to the address, the field names are different 
        // if the comp if using IPv4 or IPv6
        if (p->ai_family == AF_INET)    // IPv4
        {
            struct sockaddr_in *ipv4 = (struct sockaddr_in * )p->ai_addr;
            addr = &(ipv4->sin_addr);
            ipver = "IPv4";
        }
        else                            // IPv6
        {
            struct sockaddr_in6 *ipv6 = (struct sockaddr_in * )p->ai_addr;
            addr = &(ipv6->sin6_addr);
            ipver = "IPv6";
        }

        // Convert the ip to a string and print it
        inet_ntop(p->ai_family, addr, ipstr, sizeof(ipstr));
        printf("%s: %s\n", ipver, ipstr);
    }

    // Free the linked list generated by getaddrinfo
    freeaddrinfo(res);

    return 0;
}
